apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-faktasider-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /arbeid/api/isalive
  readiness:
    path: /arbeid/api/isready
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: 1500m
      memory: 512Mi
    requests:
      cpu: 1000m
      memory: 256Mi
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: api.sanity.io
        - host: rt6o382n.api.sanity.io
        - host: apicdn.sanity.io
        - host: rt6o382n.apicdn.sanity.io
        - host: cdn.sanity.io
        - host: dekoratoren.ekstern.dev.nav.no
        - host: amplitude.nav.no
        - host: sentry.gc.nav.no
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/pki/tls/certs/ca-bundle.crt"
    - name: DEKORATOR_MILJO
      value: {{dekoratorMiljo}}
    - name: NPM_CONFIG_CACHE
      value: /tmp
    - name: NEXT_PUBLIC_SANITY_DATASET
      value: {{sanityDataset}}
    - name: NEXT_PUBLIC_SENTRY_STAGE
      value: {{sentry_stage}}
  envFrom:
    - secret: dp-faktasider-frontend-sanity-cms-read-token
  {{ingresses}}
