apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  {{ingresses}}
