apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-faktasider-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /arbeid/api/isalive
  readiness:
    path: /arbeid/api/isready
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: rt6o382n.*.sanity.io
        - host: dekoratoren.dev.nav.no
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/pki/tls/certs/ca-bundle.crt"
    - name: DEKORATOR_MILJO
      value: {{dekoratorMiljo}}
  {{ingresses}}
