name: Build and deploy

on:
  workflow_dispatch:
  push:

env:
  IMAGE: ghcr.io/${{ github.repository }}/dp-faktasider-frontend:${{ github.sha }}
  LATEST_IMAGE: ghcr.io/${{ github.repository }}/dp-faktasider-frontend:latest

jobs:
  jest-test:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - run: npm install --no-save --no-audit --prefer-offline --ignore-scripts
        env:
          TZ: Europe/Oslo
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - run: npm rebuild && npm run prepare --if-present

        env:
          TZ: Europe/Oslo
      - run: |
          npm test
          npm run typeCheck

  cypress-test:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
        env:
          SANITY_READ_TOKEN: ${{ secrets.CYPRESS_READ_TOKEN_SANITY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com"
      - run: cp $NPM_CONFIG_USERCONFIG .npmrc

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }},${{ env.LATEST_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}"
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"

      - name: Archive NAIS yaml
        uses: actions/upload-artifact@v1
        with:
          name: nais-yaml
          path: nais

  deploy-dev-gcp:
    name: Deploy to dev gcp
    needs: [build, jest-test, cypress-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VARS: nais/dev-gcp/vars.yaml
          PRINT_PAYLOAD: true

      - name: Lag deployment i Sentry
        uses: getsentry/action-release@v1
        continue-on-error: true
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_URL: https://sentry.gc.nav.no
          SENTRY_ORG: nav
          SENTRY_PROJECT: dp-faktasider-frontend
        with:
          environment: development
          version: ${{ github.sha }}
          set_commits: skip

  deploy-prod-gcp:
    name: Deploy to prod gcp
    needs: [deploy-dev-gcp]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml
          VARS: nais/prod-gcp/vars.yaml
          PRINT_PAYLOAD: true

      - name: Lag deployment i Sentry
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_URL: https://sentry.gc.nav.no
          SENTRY_ORG: nav
          SENTRY_PROJECT: dp-faktasider-frontend
        with:
          environment: production
          version: ${{ github.sha }}
          set_commits: skip
